### ISSUE TITLE
Build Instructions.

### ISSUE THREAD

**Issue by craftxbox** [PeriodicChaos/SS13-Faithful-Remake-Lost-In-Space-Godot-Engine-#1]
Hi there, I'm not quite sure how to get started and build this project. Would you be able to write a general guide to put into the [README.md](https://github.com/PeriodicChaos/SS13-Faithful-Remake-Lost-In-Space-Godot-Engine-/tree/main/README.md) to get new people started?

**Comment by PeriodicChaos** [comment]
Sorry about that i will do that right now

**Comment by PeriodicChaos** [comment]
closed
