### ISSUE TITLE
Have you looked at the other remakes?

### ISSUE THREAD

**Issue by moonheart08** [PeriodicChaos/SS13-Faithful-Remake-Lost-In-Space-Godot-Engine-#3]
The remakes https://github.com/unitystation/unitystation (Unity game) and https://github.com/space-wizards/space-station-14 (Custom game engine, RobustToolbox) are already really far along and it may be better to focus your efforts there, rather than starting another (likely to die, SS13 is massive!) attempt at a remake.

**Comment by PeriodicChaos** [comment]
I do not think any of my ideas in SS13 unity or SS14 would be allowed to be made as this is not going to be me making the game really as i define ss13 as a wide community with different ideas as in ss13 is not just a station sometimes its just a base for other to build off of

**Comment by PeriodicChaos** [comment]
closed

**Comment by moonheart08** [comment]
> I do not think any of my ideas in SS13 unity or SS14 would be allowed to be made as this is not going to be me making the game really as i define ss13 as a wide community with different ideas as in ss13 is not just a station sometimes its just a base for other to build off of

SS14 is a remake designed and built around forking and has effectively built it's own BYOND, so I'm not sure I see what makes that impossible. It already has forks, even.
